name: app_for_trood
description: Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.3
  path_provider: ^2.0.9
  provider: ^6.0.2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  lints: ^1.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/
